import { describe, expect, it } from 'vitest';
import { createInitialState } from '../src/initialState.js';
import { migrate, migrations } from '../src/migrate.js';
import { SIM_VERSION } from '../src/version.js';
import saveV1 from './fixtures/save-v1.json' with { type: 'json' };

/**
 * The fixture is a real v1 blob, captured with
 * `psql -c "SELECT jsonb_pretty(state) FROM players LIMIT 1"` against a development
 * database that had been running Phase 0. That matters: the point of a migration test is
 * surviving saves you cannot re-create, and a blob generated by today's code has already
 * been quietly fixed by today's types.
 */
describe('migrate', () => {
  it('has one migration per version step', () => {
    expect(migrations).toHaveLength(SIM_VERSION - 1);
  });

  it('brings a real Phase 0 save forward to the current version', () => {
    const migrated = migrate(saveV1, 1);

    expect(migrated.simVersion).toBe(SIM_VERSION);
    // The field that did not exist before there was a simulation to be asleep during.
    expect(migrated.bean.asleepSinceMs).toBeNull();
    // Everything the old save did say survives verbatim.
    expect(migrated.bean.name).toBe('Pip');
    expect(migrated.bean.needs).toEqual({ hunger: 100, warmth: 100, rest: 100, mood: 100 });
    expect(migrated.worldMs).toBe(saveV1.worldMs);
    expect(migrated.rng).toEqual(saveV1.rng);
  });

  it('produces a save the current code would recognise as its own shape', () => {
    const migrated = migrate(saveV1, 1);
    const fresh = createInitialState({ beanName: 'Pip', nowMs: saveV1.worldMs, seed: 1 });

    // Same keys, top level and inside the bean — a migration that forgets a field shows up
    // here rather than as a crash three phases later.
    expect(Object.keys(migrated).sort()).toEqual(Object.keys(fresh).sort());
    expect(Object.keys(migrated.bean).sort()).toEqual(Object.keys(fresh.bean).sort());
  });

  it('does not mutate the save it is given', () => {
    const before = JSON.stringify(saveV1);
    migrate(saveV1, 1);
    expect(JSON.stringify(saveV1)).toBe(before);
  });

  it('leaves a current save untouched', () => {
    const current = createInitialState({ beanName: 'Beanie', nowMs: 0, seed: 7 });
    expect(migrate(current, SIM_VERSION)).toEqual(current);
  });

  it('leaves a save from the future alone rather than mangling it', () => {
    // Happens on a rollback. Refusing to touch it is the only safe answer.
    const future = { ...createInitialState({ beanName: 'B', nowMs: 0, seed: 7 }), simVersion: 99 };
    expect(migrate(future, 99).simVersion).toBe(99);
  });
});
